[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[chain]
chain_id="chain0"

# the failover config
# enable failover or not, default disable
enable_failover=false
# the address of etcd, can configure multiple comma-separated
failover_cluster_url = "127.0.0.1:2379"

[[group.deploy_info]]
node_name = "node2"
deploy_ip = "172.25.0.5"
expanded_service = "group0node00BcosNodeService"
node_count=1

[[group.deploy_info]]
node_name = "node3"
deploy_ip = "172.25.0.5"
expanded_service = "group0node00BcosNodeService"
node_count=1
