[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[chain]
chain_id="chain0"

[[group]]
group_id="group0"
# the genesis configuration path of the expanded group
genesis_config_path = "generated/chain0/group0/config.genesis"

# the genesis configuration path of the group, will generate new genesis configuration if not configurated
# genesis_config_path = ""
# VM type, now only support evm/wasm
vm_type="evm"
# use sm-crypto or not
sm_crypto=false
# enable auth-check or not
auth_check=false
init_auth_address=""


[[agency]]
name = "agencyA"
    [[agency.group]]
        group_id = "group0"

        [[agency.group.node]]
        # expand the existed-max-node
        node_name = "node0"
        # the tikv storage pd-addresses
        pd_addrs="172.25.0.3:2379"
        deploy_ip = ["172.25.0.5"]
        executor_deploy_ip=["172.25.0.3"]
        
        [[agency.group.node]]
        # expand a new max node
        node_name = "node1"
        # the tikv storage pd-addresses
        pd_addrs="172.25.0.5:2379"
        deploy_ip = ["172.25.0.5"]
        executor_deploy_ip=["172.25.0.5"]