name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [push]

jobs:
  build:
    name: centos ci check
    runs-on: self-hosted
    strategy:
      fail-fast: false
    env:
      VCPKG_ROOT: ~/cache/vcpkg
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: yum install
        run: |
          sudo yum install -y -q epel-release centos-release-scl flex bison patch gmp-static
          sudo yum install -y -q devtoolset-10 devtoolset-11 llvm-toolset-7 rh-perl530-perl cmake3 zlib-devel ccache lcov python-devel python3-devel
          sudo yum reinstall -y -q https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          sudo yum install -y -q git

      #- uses: hendrikmuhs/ccache-action@v1.2
      #  with:
      #    max-size: 25G

      - uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            deps/
          key: build-centos7.6-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            build-centos7.6-${{ hashFiles('.github/workflows/workflow.yml') }}
            build-centos7.6-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      # - name: Prepare vcpkg
      #  uses: lukka/run-vcpkg@v10
      #  with: { vcpkgGitCommitId: 7e3dcf74e37034eea358934a90a11d618520e139 }

      - name: Build for linux
        run: |
          ln -s ${{ env.DEPS_ROOT }} deps
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          alias cmake='cmake3'
          . /opt/rh/devtoolset-10/enable
          . /opt/rh/rh-perl530/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/lib64/
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          . /opt/rh/llvm-toolset-7/enable

          mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=On -DWITH_TARS_SERVICES=ON .. || cat *.log
          make -j8

      - name: Test
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest
          make cov

      - name: Generate covreage report
        uses: codecov/codecov-action@v3
        with:
          file: ./build/coverage.info
          name: FISCO BCOS 3.0.0 coverage
          fail_ci_if_error: true