name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]

jobs:
  build:
    name: build
    runs-on: ci-ubuntu20-docker0
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true
      - name: Prepare vcpkg
        if: runner.os == 'Linux'
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            deps/
            c:/vcpkg
            !c:/vcpkg/.git
            !c:/vcpkg/buildtrees
            !c:/vcpkg/packages
            !c:/vcpkg/downloads
          key: build-${{ matrix.os }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            build-${{ matrix.os }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            build-${{ matrix.os }}-${{ github.base_ref }}-
            build-${{ matrix.os }}-
      - name: Build for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y lcov ccache wget libgmp-dev python3-dev
          export GCC='gcc-10'
          export CXX='g++-10'
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=OFF -DWITH_TARS_SERVICES=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
          cmake --build . --parallel 3
      - name: Test
        if: runner.os == 'Linux'
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest
          make cov
      - name: Generate covreage report
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v3
        with:
          file: ./build/coverage.info
          name: FISCO BCOS 3.0.0 coverage
          fail_ci_if_error: true