name: Mac CI Check
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
    branches:
      - release-3.*
      - feature-3.*
      - master
  release:
    types: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_mac:
    name: mac ci check
    runs-on: self-hosted-mac3.4
    strategy:
      fail-fast: false
    env:
      DEPS_ROOT: ~/cache/deps3.4
      VCPKG_ROOT: ~/cache/vcpkg

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          java-package: jdk

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      - name: Reuse build cache
        run: |
          mkdir -p ./build
          rm -rf deps
          ln -s ${{ env.DEPS_ROOT }} deps

      - name: Remove cache if correspond dir change
        run: ./tools/.ci/clear_build_cache.sh

      - name: Build for mac
        run: |
          mkdir -p build && cd build && rm -rf CMakeCache.txt
          cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=OFF -DWITH_TARS_SERVICES=ON -DURL_BASE=ghproxy.com/github.com .. || cat *.log
          cmake --build . --parallel 8

      - name: Test
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=TRUE make test

      - name: Integration test - Air
        run: cd tools && bash .ci/ci_check_air.sh ${{ github.base_ref }}

      - name: Integration test - Pro
        run: cd tools && bash .ci/ci_check_pro.sh ${{ github.base_ref }}