name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [push]

jobs:
  build:
    name: build
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: apt install
        run: |
          sudo apt install -y lcov ccache wget libgmp-dev python3-dev git curl zip unzip tar

      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 25G

      - uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            deps/
          key: build-ubuntu22.04-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            build-ubuntu22.04-${{ hashFiles('.github/workflows/workflow.yml') }}
            build-ubuntu22.04-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true
      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v10
        with: { vcpkgGitCommitId: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - name: Build for linux
        run: |
          export GCC='gcc-10'
          export CXX='g++-10'
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=On -DWITH_TARS_SERVICES=ON && make -j16|| cat *.log
      - name: Test
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest
          make cov
      - name: Generate covreage report
        uses: codecov/codecov-action@v3
        with:
          file: ./build/coverage.info
          name: FISCO BCOS 3.0.0 coverage
          fail_ci_if_error: true