name: Ubuntu CI Check
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    name: ubuntu ci check
    runs-on: self-hosted-ubuntu
    strategy:
      fail-fast: false
    env:
      VCPKG_ROOT: ~/cache/vcpkg
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: apt install
        run: |
          sudo apt update
          sudo apt install -y  lcov ccache wget python3-dev git curl zip unzip tar
          sudo apt install -y --no-install-recommends \
              clang make build-essential cmake libssl-dev zlib1g-dev ca-certificates \
              libgmp-dev flex bison patch libzstd-dev ninja-build pkg-config ccache

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      - name: Reuse build cache
        run: |
          mkdir -p ./build
          rm -rf deps
          ln -s ${{ env.DEPS_ROOT }} deps

      - name: Remove cache if correspond dir change
        id: changed-files-specific
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            bcos-tars-protocol/**
      - name: Remove changed file build cache
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "bcos-tars-protocol change remove build/generated"
          rm -rf build/generated

      - name: Build for linux
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cd build && cmake -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=Off -DWITH_TARS_SERVICES=ON .. || cat *.log
          make -j8

      - name: Test
        run:
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest
