name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
        # os: [ubuntu-20.04, macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: Prepare vcpkg
        if: runner.os != 'Windows'
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            /home/runner/.cargo
            /Users/runner/.cargo/
            /home/runner/.ccache
            /Users/runner/.ccache/
            deps/src
          key: build-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            build-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            build-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            build-v8-notest-${{ runner.temp }}-
      - name: Build for windows
        if: runner.os == 'Windows'
        run: |
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DFULLNODE=OFF -DWITH_LIGHTNODE=OFF -DWITH_CPPSDK=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ../
          cmake --build . --parallel 3
      - name: Build for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y lcov ccache
          export GCC='gcc-10'
          export CXX='g++-10'
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TARS_SERVICES=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
          cmake --build . --parallel 3
      - name: Build for macos
        if: runner.os == 'macOS'
        run: |
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TARS_SERVICES=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
          cmake --build . --parallel 3
      - name: Test
        if: runner.os != 'Windows'
        run:
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest
  build_centos:
    name: build_centos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        tikv: ['WITH_TIKV=ON', 'WITH_TIKV=OFF']
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            /home/runner/.cargo
            /Users/runner/.cargo/
            /home/runner/.ccache
            /Users/runner/.ccache/
            deps/src
          key: centos-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            centos-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            centos-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            centos-v8-notest-${{ runner.temp }}-
      - name: Prepare centos tools
        run: |
          yum install yum install -y epel-release centos-release-scl flex bison
          yum install -y devtoolset-10 llvm-toolset-7 rh-perl530-perl cmake3 zlib-devel ccache
          yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          yum install -y git
      - name: Prepare vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: Build
        run: |
          alias cmake='cmake3'
          . /opt/rh/devtoolset-10/enable
          . /opt/rh/rh-perl530/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/lib64/
          . /opt/rh/llvm-toolset-7/enable
          mkdir -p build
          cd build
          cmake3 -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TARS_SERVICES=ON -D${{ matrix.tikv }} -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
          cmake3 --build . --parallel 4
      - name: Test with tikv
        if: matrix.tikv == 'WITH_TIKV=ON'
        run: |
          mkdir -p /root/.tiup/bin/
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          source /github/home/.profile
          tiup update --self && tiup update playground
          tiup clean --all
          tiup playground v5.4.2 --mode tikv-slim &
          sleep 10
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - name: Test
        if: matrix.tikv == 'WITH_TIKV=OFF'
        run:
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE make test