name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [push]

jobs:
  build:
    name: ubuntu ci check
    runs-on: self-hosted-ubuntu
    strategy:
      fail-fast: false
    env:
      VCPKG_ROOT: ~/cache/vcpkg
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: apt install
        run: |
          sudo apt update
          sudo apt install -y  lcov ccache wget python3-dev git curl zip unzip tar
          sudo apt install -y --no-install-recommends \
              clang make build-essential cmake libssl-dev zlib1g-dev ca-certificates \
              libgmp-dev flex bison patch libzstd-dev ninja-build pkg-config ccache


      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      # - name: Prepare vcpkg
      #  uses: lukka/run-vcpkg@v10
      #  with: { vcpkgGitCommitId: 7e3dcf74e37034eea358934a90a11d618520e139 }

      - name: Build for linux
        run: |
          ln -s ${{ env.DEPS_ROOT }} deps
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=On -DWITH_TARS_SERVICES=ON .. || cat *.log
          make -j8

      - name: Test
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE make test
      #    make cov

    #  - name: Generate covreage report
    #    uses: codecov/codecov-action@v3
    #    with:
    #      file: ./build/coverage.info
    #      name: FISCO BCOS 3.0.0 coverage
    #      fail_ci_if_error: true
  build:
    name: centos ci check
    runs-on: self-hosted-centos
    strategy:
      fail-fast: false
    env:
      VCPKG_ROOT: ~/cache/vcpkg
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: yum install
        run: |
          sudo yum install -y -q epel-release centos-release-scl flex bison patch gmp-static
          sudo yum install -y -q devtoolset-10 devtoolset-11 llvm-toolset-7 rh-perl530-perl cmake3 zlib-devel ccache lcov python-devel python3-devel
          sudo yum reinstall -y -q https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          sudo yum install -y -q git

      #- uses: hendrikmuhs/ccache-action@v1.2
      #  with:
      #    max-size: 25G

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      # - name: Prepare vcpkg
      #  uses: lukka/run-vcpkg@v10
      #  with: { vcpkgGitCommitId: 7e3dcf74e37034eea358934a90a11d618520e139 }

      - name: Build for linux
        run: |
          ln -s ${{ env.DEPS_ROOT }} deps
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          . /opt/rh/devtoolset-10/enable
          . /opt/rh/rh-perl530/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/lib64/
          . /opt/rh/llvm-toolset-7/enable
          alias cmake='cmake3'
          mkdir -p build && cd build && cmake3 -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=Off -DWITH_TARS_SERVICES=ON .. || cat *.log
          make -j8

      - name: Test
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE make test
      #    make cov

    #  - name: Generate covreage report
    #    uses: codecov/codecov-action@v3
    #    with:
    #      file: ./build/coverage.info
    #      name: FISCO BCOS 3.0.0 coverage
    #      fail_ci_if_error: true